# version: 2.1

# jobs:
#   # Job one with a unique name
#   say_hello:
#     docker:
#      - image: cimg/base:2022.05
#     steps:
#       - run: echo "Say hello to YAML!"
#   # Job two with a unique name
#   say_goodbye:
#     docker:
#      - image: cimg/base:2022.05
#     steps:
#       - run: echo "Say goodbye to YAML!"


# workflows:
#   # Name of workflow
#   hello_and_goodbye:
#     # List of jobs that will run
#     jobs:
#       - say_hello
#       - say_goodbye
    
version: 2.1

jobs:
  # Job one with a unique name
  say_hello:
    working_directory: ~/tmp/project
    docker:
     - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: The First Step TO A START
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file terraform.tfvars
  # Job two with a unique name
  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run:
          name: The First Step TO A START
          command: |
            ls -al
            echo '^^^The files in your repo^^^' 
 
 jobs:
  # Job one with a unique name
  wtf:
    working_directory: ~/tmp/project
    docker:
     - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: random commands 
          command: |
            ip a 
            
workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - say_hello
      - say_goodbye
  part_and_part:
    # List of jobs that will run 2222 
    jobs:
      - wtf
