version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ~/project2
      - terraform/validate:
          path: ~/project2
      - terraform/fmt:
          path: ~/project2
      - terraform/plan:
          path: ~/project2
      - terraform/apply:
          path: ~/project2
      - terraform/destroy:
          path: ~/project2
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle


