version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: noice
      - terraform/validate:
          checkout: true
          context: noice
          requires:
            - noice/fmt
      - terraform/plan:
          checkout: true
          context: noice
          persist-workspace: true
          requires:
            - noice/validate
      - terraform/apply:
          attach-workspace: true
          context: noice
          filters:
            branches:
              only: main
          requires:
            - noice/plan
