
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#     steps:
#       - checkout # check out the code in the project directory
#       - run: echo "hello world" # run the `echo` command
#       - run: echo "hello worlsdfsdfd" # run the `echo` command

# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  say_hello:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: terraform apply --auto-approve


workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - say_hello

